#!/bin/bash

IMAGE_PATH = "/home/friedmicro/Pictures/wallpaper.jpg"
SCREEN_HEIGHT = 1440
SCREEN_WIDTH = 2560
DEVICE_ID = "desktop"
SERVER_IP = 192.168.1.44
SERVER_PORT = 3500

curl -X POST http://$SERVER_IP:$SERVER_PORT/image -H "Content-Type: application/json" -d '{"min_x": $SCREEN_WIDTH, "min_y": $SCREEN_HEIGHT, "device": $DEVICE_ID}' > $IMAGE_PATH

rand_image=$IMAGE_PATH
rand_image=$( printf "%s\n" "$rand_image" | sed 's/ /%20/g' )
rand_image="file://"$rand_image
echo $rand_image
gsettings set org.gnome.desktop.background picture-uri $rand_image
gsettings set org.gnome.desktop.background picture-uri-dark $rand_image
gsettings set org.gnome.desktop.screensaver picture-uri $rand_image
gsettings set org.gnome.desktop.screensaver picture-uri-dark $rand_image
